{"name": "test_add[get_add_datas3]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase.py:23: AssumptionFailure\n>>\tpytest.assume(result == get_add_datas[2])\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase.py:23: AssumptionFailure\nE               >>\tpytest.assume(result == get_add_datas[2])\nE               AssertionError: assert False\n\n..\\..\\venv\\lib\\site-packages\\six.py:702: FailedAssumption"}, "steps": [{"name": "加法验证", "status": "passed", "start": 1609591371415, "stop": 1609591371423}], "parameters": [{"name": "get_add_datas", "value": "[-1, 'a', 'None']"}], "start": 1609591371414, "stop": 1609591371411, "uuid": "e89b4875-b8d1-433d-aee6-db43f5ae74c7", "historyId": "f5e0fe60fff8d461e02003eba3012724", "testCaseId": "ab5d951d5569ee8f7ed544d649962dff", "fullName": "testcase.TestAdd#test_add", "labels": [{"name": "story", "value": "加法测试"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "flaky(reruns=2)"}, {"name": "suite", "value": "testcase"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "PC-20150415WRCK"}, {"name": "thread", "value": "5644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase"}]}