{"name": "test_div[get_div_datas2]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase.py:43: AssumptionFailure\n>>\tpytest.assume(result == get_div_datas[2])\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase.py:43: AssumptionFailure\nE               >>\tpytest.assume(result == get_div_datas[2])\nE               AssertionError: assert False\n\n..\\..\\venv\\lib\\site-packages\\six.py:702: FailedAssumption"}, "steps": [{"name": "除法验证", "status": "passed", "start": 1609591384099, "stop": 1609591384107}], "parameters": [{"name": "get_div_datas", "value": "[4, 0, 2]"}], "start": 1609591384099, "stop": 1609591384098, "uuid": "7b39c212-c563-4bed-80b6-c56476dc641c", "historyId": "20cf75dc88a58efbb82c074e9b780739", "testCaseId": "ee3bd6e736bfc2a71d2922fb59303410", "fullName": "testcase.TestDiv#test_div", "labels": [{"name": "story", "value": "除法测试"}, {"name": "tag", "value": "run(order=4)"}, {"name": "tag", "value": "flaky(reruns=5, reruns_delay=3)"}, {"name": "suite", "value": "testcase"}, {"name": "subSuite", "value": "TestDiv"}, {"name": "host", "value": "PC-20150415WRCK"}, {"name": "thread", "value": "5644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase"}]}